inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

RSpec/FilePath:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Metrics/ClassLength:
  Max: 1500

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false


Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/QuotedSymbols:
  EnforcedStyle: same_as_string_literals

Style/Documentation:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Lint/ShadowingOuterLocalVariable:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'lib/tasks/**/*'
    - 'test/**/*'
  SuggestExtensions: false
